[package]
name = "mesh-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
mesh-parser = { path = "../mesh-parser" }
mesh-common = { path = "../mesh-common" }
rowan = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
