[package]
name = "mesh-lexer"
version = "0.1.0"
edition = "2021"
description = "Tokenizer for the Mesh programming language"

[dependencies]
mesh-common = { path = "../mesh-common" }

[dev-dependencies]
insta = { workspace = true }
serde = { workspace = true }
