[package]
name = "mesh-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
mesh-common = { path = "../mesh-common" }
mesh-lexer = { path = "../mesh-lexer" }
rowan = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde = { workspace = true }
